version: "3"

services:
  us-srv-db:
    build: 
      context: .
      dockerfile: url_repo_db.dockerfile
    container_name: us-srv-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: url_repo_db

  us-service:
    build:
      context: .
      dockerfile: us-service.dockerfile
    container_name: us-service
    ports:
      - 80:8080
    depends_on:
      - us-srv-db    